config/routes.rb
Rails.application.routes.draw do  
  resources :imports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
class Import < ApplicationRecord
    has_many :vendas, dependent: :destroy
    def import(import_file)  
        @import = Import.create()
        total_imports = 0
        total_price = 0
        File.foreach( import_file.path ).with_index do |line, index| 
            next if index == 0           
            fields = line.split("\t")           
            venda = @import.vendas.new(comprador: fields[0], descricao: fields[1], preco_unitario: fields[2], quantidade: fields[3], endereco: fields[4], fornecedor: fields[5])
            if venda.save
                total_imports = total_imports + 1
                total_price = total_price + fields[2].to_i
            end            
        end
        @import.update(total_imports: total_imports, total_price: total_price)
        return @import
    end
end

app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :import
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: %i[ show edit update destroy ]

  # GET /imports or /imports.json
  def index
    @imports = Import.all
  end

  # GET /imports/1 or /imports/1.json
  def show
    @import = Import.find(params[:id])
    @vendas = @import.vendas
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # POST /imports or /imports.json
  def create
    @import = Import.new().import(import_params[:import_file])
    @vendas = @import.vendas

    respond_to do |format|    
        format.html { redirect_to @import, notice: "Arquivo foi importado com sucesso!" }
        format.json { render :show, status: :created, location: @import, vendas: @vendas }      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def import_params
      params.permit(:import_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/imports/_form.html.erb
<%= form_with(model: import, local: true, html: { multipart: true }) do |form| %>
  <% if import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= file_field_tag :import_file %>
  <br />
  <br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imports</h1>

<table>
  <thead>
    <tr>
      <th>Total imports</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <td><%= import.total_imports %></td>
        <td><%= import.total_price %></td>
        <td><%= link_to 'Show', import %></td>       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Import', new_import_path %>

app/views/imports/new.html.erb
<h1>New Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Back', imports_path %>

app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total imports:</strong>
  <%= @import.total_imports %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @import.total_price %>
</p>

<h1>Vendas importadas</h1>

<table>
  <thead>
    <tr>
      <th>Comprador</th>
      <th>Descricao</th>
      <th>Preco unitario</th>
      <th>Quantidade</th>
      <th>Endereco</th>
      <th>Fornecedor</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.comprador %></td>
        <td><%= venda.descricao %></td>
        <td><%= venda.preco_unitario %></td>
        <td><%= venda.quantidade %></td>
        <td><%= venda.endereco %></td>
        <td><%= venda.fornecedor %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', imports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>